SELECT TOP (1000) [ID]
      ,[supplierName]
      ,[supplierContactName]
      ,[supplierContactEmail]
      ,[supplierContactPhone]
      ,[supplierContactLang]
      ,[supplierLeavePending]
      ,[supplierReturnsContactName]
      ,[supplierReturnsContactEmail]
      ,[workdaysToDeliver]
      ,[discountPP]
      ,[discountAffectIva]
      ,[cobraIva]
      ,[daysToPay]
      ,[contributeToLeadTime]
      ,[isActive]
      ,[obsPrivate]
      ,[obsShared]
  FROM [sweet].[dbo].[suppliersName]