-- Active: 1709306145245@@127.0.0.1@3306@invoicedb
SELECT * FROM Regex WHERE nome_empresa = 'Roger & Gallet';
SELECT * FROM Regex WHERE nome_empresa = 'Moreno II';
SELECT * FROM Regex;
--most recent select returned :
--2,Roger & Gallet,\bRoger\s*&\s*Gallet\b,\b\d{2}[/-]\d{2}[/-]\d{4}|\d{4}[/-]\d{2}[/-]\d{2}\b,\b[A-Za-z]+\d+CRM\d+\b,\b[A-Za-z]+\d+FAC\d+\b,\b\d{2}[/-]\d{2}[/-]\d{4}|\d{4}[/-]\d{2}[/-]\d{2}\b,"Total sem IVA\s*([\d,]+)\s*",Padrão Regex para Totais por IVA,IVA\s*%?\s*(d+(?:\.\d+)?)s+\d+(?:\.\d+)?,Padrão Regex para Desconto Pronto Pagamento,"Total com IVA\s*([\d,]+)\s*EUR","(?<Article>\w+)\s+(?<Barcode>\d+)\s+(?<Description>.+?)\s+(?<Quantity>\d+)\s+(?<GrossPrice>[\d,]+)\s+(?<Discount>[\d,]+)\s+(?<PrecoSemIVA>[\d,]+)\s+(?<PrecoComIVA>[\d,]+)",Padrão Regex para Taxa de IVA
--3,MORENO II,\bMORENO\s*+II\b,\b\d{2}[.-]\d{2}[.-]\d{4}|\d{4}[/-]\d{2}[/-]\d{2}\b,Sweetcare\s+Nº\s*:\s*(\d+),(?<=Fatura Nº\s)\d+,Vencimento:\s*\b\d{2}[\/\.-]\d{2}[\/\.-]\d{4}|\d{4}[\/\.-]\d{2}[\/\.-]\d{2}\b,"(?<=Base de Incidência:\s*)([\d,]+)",Padrão Regex para Totais por IVA,IVA\s*%?\s*(d+(?:\.\d+)?)s+\d+(?:\.\d+)?,Padrão Regex para Desconto Pronto Pagamento,"([\d,]+)\s*TOTAL","(?<Article>\w+)\s+(?<Barcode>\d+)\s+(?<Description>.+?)\s+(?<Quantity>\d+)\s+(?<GrossPrice>[\d,]+)\s+(?<Discount>[\d,]+)\s+(?<PrecoSemIVA>[\d,]+)\s+(?<PrecoComIVA>[\d,]+)",Padrão Regex para Taxa de IVA
--4,LABORATORIOS EXPANSCIENCE,LABORATORIOS EXPANSCIENCE,(\d{4}-\d{2}-\d{2}),(?<=N\s+encomen\s+\w+\s+\w+\s+\w+\s+\w+\s+\w+\s+\w+\s)(\d+),Fatura\s*Nº\s*:\s*(\d+),Vencimento:\s*\b\d{2}[\/\.-]\d{2}[\/\.-]\d{4}|\d{4}[\/\.-]\d{2}[\/\.-]\d{2}\b,"Total sem IVAs*([\d,]+)\s*",Padrão Regex para Totais por IVA,IVA\s*%?\s*(d+(?:\.\d+)?)s+\d+(?:\.\d+)?,Padrão Regex para Desconto Pronto Pagamento,"Total com IVA\s*([\d,]+)\s*EUR",(\w+)\s+([A-Z\s\d\-\+ML%]+)\s+(\d+)\s+([\w\-]+)\s+(\d+\sUN)\s+(\d+\.\d{2})\s+(\d+\.\d{2})\s+(\d+\.\d{2})\s+(\d),Padrão Regex para Taxa de IVA
--- 1710321482829 pc
--- home pc 1709306145245